### ISSUE TITLE
Getting Document is not defined error 

### ISSUE THREAD

**Issue by juliojerrick** [bkzl/vue-fraction-grid#10]
Enviroment:

Using nuxt.js : https://nuxtjs.org/

This is the trace:

Nuxt.js Error:

ReferenceError: document is not defined
    at a (/Users/jerrickmedia/Documents/jerrick-new/node_modules/vue-fraction-grid/dist/vue-fraction-grid.js:1:2656)
    at r (/Users/jerrickmedia/Documents/jerrick-new/node_modules/vue-fraction-grid/dist/vue-fraction-grid.js:1:2256)
    at t.exports (/Users/jerrickmedia/Documents/jerrick-new/node_modules/vue-fraction-grid/dist/vue-fraction-grid.js:1:4094)
    at Object.<anonymous> (/Users/jerrickmedia/Documents/jerrick-new/node_modules/vue-fraction-grid/dist/vue-fraction-grid.js:1:24299)
    at e (/Users/jerrickmedia/Documents/jerrick-new/node_modules/vue-fraction-grid/dist/vue-fraction-grid.js:1:396)
    at Object.<anonymous> (/Users/jerrickmedia/Documents/jerrick-new/node_modules/vue-fraction-grid/dist/vue-fraction-grid.js:1:6810)
    at e (/Users/jerrickmedia/Documents/jerrick-new/node_modules/vue-fraction-grid/dist/vue-fraction-grid.js:1:396)
    at Object.<anonymous> (/Users/jerrickmedia/Documents/jerrick-new/node_modules/vue-fraction-grid/dist/vue-fraction-grid.js:1:12225)
    at e (/Users/jerrickmedia/Documents/jerrick-new/node_modules/vue-fraction-grid/dist/vue-fraction-grid.js:1:396)
    at Object.defineProperty.value (/Users/jerrickmedia/Documents/jerrick-new/node_modules/vue-fraction-grid/dist/vue-fraction-grid.js:1:779)
    at /Users/jerrickmedia/Documents/jerrick-new/node_modules/vue-fraction-grid/dist/vue-fraction-grid.js:1:789
    at n (/Users/jerrickmedia/Documents/jerrick-new/node_modules/vue-fraction-grid/dist/vue-fraction-grid.js:1:143)
    at Object.<anonymous> (/Users/jerrickmedia/Documents/jerrick-new/node_modules/vue-fraction-grid/dist/vue-fraction-grid.js:1:273)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

**Comment by juliojerrick** [comment]
@bkzl I can make it work by adding ssr:false configuration option but obviously I need it to work on the SSR.

**Comment by juliojerrick** [comment]
@bkzl Is there any quick fix for this?

**Comment by bkzl** [comment]
Not really. I'll try to check this on the upcoming weekend.

**Comment by juliojerrick** [comment]
@bkzl Does the latest release fix this issue?

**Comment by bkzl** [comment]
@juliojerrick Sorry I didn't have time to do that. As a quick fix you can load the plugin like this:

```js
// ./plugins/vue-fraction-grid.js

import Vue from 'vue'
import VueFractionGrid from '../node_modules/vue-fraction-grid/vue-fraction-grid'

Vue.use(VueFractionGrid)
```

It should help for now.
