### ISSUE TITLE
Doesn't work with SSR

### ISSUE THREAD

**Issue by sebastianmacias** [bkzl/vue-fraction-grid#6]
When a try to render a page I keep getting errors like this:

```javascript

/home/dev/go/src/bitbucket.org/latamvapor/vape-city/website/node_modules/vue-fraction-grid/vue-fraction-grid.js:1
(function (exports, require, module, __filename, __dirname) { import Container from './components/Container'
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at r (/home/dev/go/src/bitbucket.org/latamvapor/vape-city/website/node_modules/vue-server-renderer/build.js:6832:16)
    at Object.<anonymous> (__vue_ssr_bundle__:22165:18)
```

Thanks

**Comment by bkzl** [comment]
How can I reproduce that? What's your setup? Do you use babel to create your server-side bundle?
